# Generated by Django 4.1 on 2022-08-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='resume',
            field=models.FileField(upload_to='resume/', verbose_name='resume'),
        ),
    ]
