# Generated by Django 4.1 on 2022-08-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_educationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='faculty',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='faculty'),
        ),
    ]
