# Generated by Django 4.1 on 2022-08-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_educationmodel_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=80, verbose_name='company')),
                ('position', models.CharField(max_length=50, verbose_name='position')),
                ('short_description', models.TextField(verbose_name='short_description')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='place',
            field=models.CharField(max_length=100, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='short_description',
            field=models.TextField(verbose_name='short_description'),
        ),
    ]
