# Generated by Django 4.1 on 2022-08-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('blog', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
