# Generated by Django 4.1 on 2022-12-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_socialmediamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='phone',
            field=models.BigIntegerField(default=0, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
