# Generated by Django 4.1 on 2023-02-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_contactmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='resume_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
