# Generated by Django 4.1 on 2023-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_resumemodel_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='phone'),
        ),
    ]
