# Generated by Django 4.1 on 2023-06-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_contactmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end_date'),
        ),
    ]
